version: "3.3"

services:
  cherrpy:
    build:
      context: .
      cache_from:
      - python:3.6-alpine
    image: cherrypy
    volumes:
      - ".:/tutorial"
    ports:
    - "8080:8080"
    # command could be some develoment server
    command: python $CHERRYPY_APP
