version: '3'
services:
  tut01:
    image: ecelis/cherrypy
    ports:
      - "8081:8080"
    command: python tut01_helloworld.py

  tut02:
    image: ecelis/cherrypy
    ports:
      - "8082:8080"
    command: python tut02_expose_methods.py

  tut03:
    image: ecelis/cherrypy
    ports:
      - "8083:8080"
    command: python tut03_get_and_post.py

  tut04:
    image: ecelis/cherrypy
    ports:
      - "8084:8080"
    command: python tut04_complex_site.py

  tut05:
    image: ecelis/cherrypy
    ports:
      - "8085:8080"
    command: python tut05_derived_objects.py

  tut06:
    image: ecelis/cherrypy
    ports:
      - "8086:8080"
    command: python tut06_default_method.py

  tut07:
    image: ecelis/cherrypy
    ports:
      - "8087:8080"
    command: python tut07_sessions.py

  tut08:
    image: ecelis/cherrypy
    ports:
      - "8088:8080"
    command: python tut08_generators_and_yield.py

  tut09:
    image: ecelis/cherrypy
    ports:
      - "8089:8080"
    command: python tut09_files.py

  tut10:
    image: ecelis/cherrypy
    ports:
      - "8090:8080"
    command: python tut10_http_errors.py
